name: drift
repository: https://github.com/simolus3/moor

packages:
  - docs/*
  - docs/assets/path_provider/*
  - drift/*
  - drift_dev/*
  - moor/*
  - moor_flutter/*
  - moor_generator/*
  - moor_generator/*
  - sqlparser/*
  - extras/**

scripts:
  analyze:
    run: dart analyze --fatal-infos --fatal-warnings .
    description: Run Dart analyzer.

  format:
    run: dart format -o write .
    description: Run Dart formatter.

  build_runner:build:
    run: |
      melos exec -- \
        "dart pub get && dart pub run build_runner build --delete-conflicting-outputs"
    description: Run a build_runner build in the example apps.
    select-package:
      depends-on: "build_runner"

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on master branch.
    branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
