name: moor_generator
description: Moor has been renamed to Drift.
version: 4.6.1
repository: https://github.com/simolus3/moor
homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.1.0
  drift_dev: ^1.0.0
  # When users depend on the latest moor_generator, they should also get the latest moor for
  # the migration to work
  moor: ^4.6.0

executables:
  moor_generator:
