name: moor_documentation
description: Documentation of the moor packages
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  docsy:
    hosted: https://simonbinder.eu
    version: ^0.2.2

dev_dependencies:
  build: ^2.1.0
  build_runner: ^2.0.5
  build_web_compilers: ^3.2.0
  built_site:
    hosted: https://simonbinder.eu
    version: ^0.2.5
  linkcheck: ^2.0.19
  shelf: ^1.2.0
  shelf_static: ^1.1.0

  moor:
  moor_generator:
  sqlparser:
  drift:
  drift_dev:

dependency_overrides:
  # todo: Remove after https://github.com/dart-lang/mime/pull/43
  mime:
    git:
      url: https://github.com/simolus3/mime.git
      ref: woff2
