name: drift
description: Drift is a reactive library to store relational data in Dart and Flutter applications.
version: 1.5.0-dev
repository: https://github.com/simolus3/moor
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  async: ^2.5.0
  convert: ^3.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  stream_channel: ^2.1.0
  sqlite3: ^1.5.1

dev_dependencies:
  build_test: ^2.0.0
  build_runner_core: ^7.0.0
  build_verify: ^3.0.0
  drift_dev: any
  uuid: ^3.0.0
  path: ^1.8.0
  build_runner: ^2.0.0
  test: ^1.17.0
  mockito: ^5.0.7
  rxdart: ^0.27.0

# TODO remove before publishing
# TODO even though we use Melos build_runner doesn't have options not to do a pub check
# TODO so always fails with:
# TODO "The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "dart pub get" again.""
dependency_overrides:
  drift_dev:
    path: ../drift_dev
  sqlparser:
    path: ../sqlparser
